### PR TITLE
Add nlmixr2 to the list

### PR DESCRIPTION
**Pull request by mattfidler**
`nlmixr2()` is also on CRAN and supports nonlinear mixed effects modeling coupled with ODE solving

### CODE REVIEW

**Comment by mattfidler** [comment]
I thought there were some `ODE` calculators in the list but I couldn't see them.  `nlmixr2::nlmixr2()` also supports ODE solving

**Comment by bbolker** [comment]
Did you look under "differential equations"? The only package listed there ATM is `mixesde`, since `nlmeODE` was [archived in May 2022](https://cran.r-project.org/web/packages/nlmeODE/index.html). Stan can fit ODEs with random-effects parameters, of course, but I don't think there's a front-end for it ...

**Comment by mattfidler** [comment]
There is stanette and torstan as front ends to ode solving in stan. I can add them too

**Comment by bbolker** [comment]
Yes please ...

**Comment by mattfidler** [comment]
Should I mention that nlmixr can run nlme models as a front end

**Comment by mattfidler** [comment]
Like nlmeode

**Comment by bbolker** [comment]
might as well, as long as the comment is brief and useful.

**Comment by bbolker** [comment]
We were thinking about adding a "packages to watch" document (like these examples, packages that had been archived but could return or packages under development/not yet on CRAN), to check periodically ... (I think I'll  add a separate issue for this).

**Comment by mattfidler** [comment]
Thanks @bbolker

**Pull request merged**
